# Theme settings
doks:
    baseurl:
    color_theme: blue
    header:
        logo:
            text: Cyber Warfare Today
            image:
        nav:
            - item_name: About
              item_url: '/about'
            - item_name: Glossary
              item_url: '/glossary'
            - item_name: Articles
              item_url: '/articles'
            - item_name: Patreon
              item_url: '#'
    footer:
        content:
            logo:
                text: Cyber Warfare Today
                image:
            copyright: <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a> | <a href="/privacy-policy">Privacy Policy</a> | <a href="mailto:cyberwarfaretoday@gmail.com">Contact</a>
        social_list:
            - network_name: twitter
              profile_url: 'https://twitter.com/krisbolton'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
